# Update tags based on yml version
name: "Update tags"

# don't allow multiple 'identical' processes to run. A second push should cancel the job from the first one.
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ github.event.inputs.pypi }}-${{ github.event.inputs.testpypi }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:

  update-tag:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: python
        with:
          python-version: '3.10' 
          update-environment: false

      - name: Get version
        id: get-version
        shell: bash
        run: |
          ${{ steps.python.outputs.python-path }} -m venv /tmp/semver-to-tag
          source /tmp/semver-to-tag/bin/activate
          pip install ruamel.yaml
          echo "action path: ${{ github.action_path }}"
          python "${{ github.action_path }}/get_version.py"

      - name: Update git tags
        uses: ajparsons/semver-to-tag@main
        with:
          semver: ${{ steps.get-version.outputs.action_version }}"
          update_tags: true
